---
apiVersion: v2
name: s3gw
version: 0.1.2
kubeVersion: ">=1.14"
description: |
  Standalone S3-compatible gateway based on Ceph RGW using a non-RADOS storage
  backend.
type: application
keywords:
  - storage
  - s3
sources:
  - https://github.com/aquarist-labs/s3gw-charts
  - https://github.com/aquarist-labs/s3gw-core
  - https://github.com/aquarist-labs/ceph
dependencies:
  - name: ingress-nginx
    version: 4.1.3
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.nginx.install
  - name: traefik
    version: 10.20.1
    repository: https://helm.traefik.io/traefik
    condition: ingress.traefik.install
maintainers:
  - name: m-ildefons  # Moritz Röhrich
    email: moritz.rohrich@suse.com
    url: https://github.com/m-ildefons
appVersion: "latest"
deprecated: false
annotations:
  app.aquarist-labs.io/name: s3gw
