---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Chart.Name }}-ingress-secret'
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{ .Values.tls.crt }}
  tls.key: |
    {{ .Values.tls.key }}
