{{ if eq .Values.storageType "local" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-local-pvc'
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: '{{ .Release.Name }}.{{ .Release.Namespace }}-local-pv'
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.storage }}
{{ end }}
