---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Chart.Name }}-secret'
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  RGW_DEFAULT_USER_ACCESS_KEY: {{ .Values.access_key | quote }}
  RGW_DEFAULT_USER_SECRET_KEY: {{ .Values.secret_key | quote }}
