{{- if .Values.ui.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Chart.Name }}-ui'
  namespace: {{ .Release.Namespace }}
  labels:
    app.aquarist-labs.io/name: '{{ .Chart.Name }}-ui'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.aquarist-labs.io/name: '{{ .Chart.Name }}-ui'
  strategy: {}
  template:
    metadata:
      labels:
        app.aquarist-labs.io/name: '{{ .Chart.Name }}-ui'
    spec:
      containers:
        - name: s3gw-ui
          image:
            '{{ .Values.imageRegistry_ui }}/{{ .Values.imageName_ui }}:{{ .Values.imageTag_ui }}'
          imagePullPolicy: {{ .Values.imagePullPolicy_ui }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: s3gw-config
            - secretRef:
                name: s3gw-secret
{{- end }}
