{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Chart.Name }}-ui-svc'
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.aquarist-labs.io/name: '{{ .Chart.Name }}-ui'
  ports:
    - name: webui
      protocol: TCP
      port: 80
      targetPort: 8080
{{- end }}
